### ISSUE TITLE
Introduced Myself as It!

### ISSUE THREAD

**Issue by thurtea** [limalib/lima#20]
![Screenshot 2024-10-25 113423](https://github.com/user-attachments/assets/5d76acda-9c55-4b43-8728-4e9d7f5d7dc7)

**Comment by tsathoqqua** [comment]
Thurtea also suggests that it would be nice to do "introduce to <person>" and "introduce yourself to <person>". Will try to support those as well.

**Comment by tsathoqqua** [comment]
`~/cmds/>introduce
Introduce who?
~/cmds/>introduce yourself
You introduce yourself as "Tsath".
~/cmds/>introduce myself
You introduce yourself as "Tsath".
~/cmds/>introduce to ithagua
You introduce yourself to Ithagua.
~/cmds/>introduce myself to ithagua
You introduce yourself to Ithagua.
~/cmds/>introduce yourself to ithagua
You introduce yourself to Ithagua.
~/cmds/>`

https://github.com/limalib/lima/commit/718ce950ad3273d549fef0656ffd191f2bbf5d4f
