### ISSUE TITLE
Comma after User MSG_Home

### ISSUE THREAD

**Issue by thurtea** [limalib/lima#21]
![image](https://github.com/user-attachments/assets/02104e67-23a1-4e64-b223-b76e97df6ee0)

Not sure why but there is a comma after the period for the home message to other players in the room.

**Comment by tsathoqqua** [comment]
@thurtea It's okay to not include screenshot, they will fill up your github account.
Just copy in the text into a code segment It's the "< >" icon in the toolbar when reporting things.

Was a superflous comma in /data/messages/living-default.
After pulling this change, do:

`@MESSAGES_D->refresh_messages()`

This will make all people who didn't override their "home" message use the new default without the comma.
