### ISSUE TITLE
/cmds/player/who.c will have space below, always fixed by updating

### ISSUE THREAD

**Issue by thurtea** [limalib/lima#23]
![image](https://github.com/user-attachments/assets/30f57660-2791-4c6d-86c3-0609c487f66e)

**Comment by tsathoqqua** [comment]
So far, not sure how to reproduce.

**Comment by thurtea** [comment]
I think it must be something within the who.c I’ll take a loookSent from my iPhoneOn Nov 5, 2024, at 12:01 PM, Tsathoggua of Nkai ***@***.***> wrote:﻿
So far, not sure how to reproduce.

**Comment by tsathoqqua** [comment]
I can reproduce in both people and who commands who both use the column features in M_FRAMES. It's an M_FRAMES issue, just haven't spotted why it is so fleeting whenever I update the commands.

**Comment by tsathoqqua** [comment]
I added a fix for this *I think*. Testing.
