### ISSUE TITLE
METHOD_D should use data from /data/config/methods

### ISSUE THREAD

**Issue by tsathoqqua** [limalib/lima#30]
METHOD_D uses a hardcoded mapping right now for go method aliases. This should be changed from:

```
                      "descend":({
                                   "descend",
                                   "climb down",
                                   "go down",
                               }),
                      "ascend":({
                                   "ascend",
                                   "climb up",
                                   "go up",
                               }),
```
to use a config file like:

```
descend:climb down,go down
ascend:climb up, go up
```
stored under /data/config/methods and read upon `create()`. It could follow the same pattern as used in DAMAGE_D.

It seems like the key name is always stored in the mapping, that can be part of reading the values from the file and creating the mapping. Notice I removed them from the config file example above.

**Comment by salterryanjr** [comment]
created the methods in /data/config

**Comment by tsathoqqua** [comment]
https://github.com/limalib/lima/commit/bd4600a49240da1323894ae1ed5ac133f8b068f6

**Comment by tsathoqqua** [comment]
A second fix was needed: https://github.com/limalib/lima/commit/46f66318c74793bc780f612d0c2e9f6f48bc2875

**Comment by tsathoqqua** [comment]
Reopening to make sure this is fixed.
