### ISSUE TITLE
[errors] *Parse accepted, but no do_* function found in object /cmds/verbs/go!

### ISSUE THREAD

**Issue by thurtea** [limalib/lima#32]
![image](https://github.com/user-attachments/assets/8c26b242-3f4c-4395-b100-33bd2c384bdd)

**Comment by tsathoqqua** [comment]
This is strange. This was changed from sorcery guild to yakitori since the yakitori guild exists.
@thurtea could you do:
`@GUILD_D->query_guilds()`
and comment the output here?

**Comment by tsathoqqua** [comment]
No reply from reporter. Closing.
