### ISSUE TITLE
More and better spell examples

### ISSUE THREAD

**Issue by tsathoqqua** [limalib/lima#9]
This was part of the TODO found in LIMA from the 1990s.

**Comment by salterryanjr** [comment]
Design Doc started

**Comment by salterryanjr** [comment]
Extended m_damage_sources to include magic_skill_used

**Comment by tsathoqqua** [comment]
https://github.com/limalib/lima/commit/eee6cf97d79b19f48c38945291b522915d47dba0

**Comment by salterryanjr** [comment]
Taking a small break to formulate next steps

**Comment by tsathoqqua** [comment]
https://github.com/limalib/lima/commit/6695cc70e7f3bbbb6543bc212f14189e44a05bf0
